Repository KUIT-HealthMate/HealthMate-Backend, pull requests merged in 2024-07, with the labels that each got.

#16 [Feat] challenge common logic 인터페이스 설계
  .github/workflows/backend-dev-ci.yml
  src/main/java/com/kuit/healthmate/challenge/common/controller/CommonChallengeController.java
  src/main/java/com/kuit/healthmate/challenge/common/dto/ChallengeResponse.java
  src/main/java/com/kuit/healthmate/challenge/common/dto/HabitItem.java
  src/main/java/com/kuit/healthmate/challenge/common/dto/SupplementAchievementStatus.java
  src/main/java/com/kuit/healthmate/challenge/common/dto/SupplementItem.java
  src/main/java/com/kuit/healthmate/challenge/common/service/CommonChallengeService.java
  src/main/java/com/kuit/healthmate/challenge/common/service/CommonChallengeServiceImpl.java
Labels: 기능 추가, ci/cd

#17 refactor : 습관 체크 api
  src/main/java/com/kuit/healthmate/challenge/habit/controller/habitController.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/Habit.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/HabitChecker.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/GetHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/GetHabitResponse.java
  src/main/java/com/kuit/healthmate/challenge/habit/repository/HabitRepository.java
  src/main/java/com/kuit/healthmate/challenge/habit/service/HabitService.java
  src/main/java/com/kuit/healthmate/user/domain/User.java
  src/test/java/com/kuit/healthmate/HabitTest.java
  src/test/java/com/kuit/healthmate/habit/HabitTest.java
Labels: 테스트 추가, 리팩토링

#23 [Refactor] Controller에 특정 HandlerAdvice만 붙이기
  src/main/java/com/kuit/healthmate/challenge/supplement/controller/SupplementController.java
  src/main/java/com/kuit/healthmate/global/exception_handler/GlobalExceptionHandler.java
  src/main/java/com/kuit/healthmate/global/exception_handler/HabitExceptionHandler.java
  src/main/java/com/kuit/healthmate/global/exception_handler/SupplementExceptionHandler.java
  src/main/java/com/kuit/healthmate/global/exception_handler/UserExceptionHandler.java
  src/test/java/com/kuit/healthmate/HealthMateApplicationTests.java
Labels: 리팩토링

#22 [Feat] 건강진단 엔티티 생성
  src/main/java/com/kuit/healthmate/diagnosis/dto/LifeStyleDto.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/MealPatternDto.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/PostDiagnosisRequest.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/SleepPatternDto.java
  src/main/java/com/kuit/healthmate/diagnosis/life/domain/LifeStyleQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/meal/domain/MealPatternQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/sleep/domain/SleepPatternQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/symtom/domain/SymptomInfo.java
  src/main/java/com/kuit/healthmate/diagnosis/symtom/domain/SymptomQuestionnaire.java
Labels: 엔티티
