Repository KUIT-HealthMate/HealthMate-Backend, pull requests merged in 2024-08, with the labels that each got.

#25 [Feat] ChatGPT api를 이용한 건강 진단 로직 구현
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-dev-ci.yml
  src/main/java/com/kuit/healthmate/chatgpt/controller/GPTController.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/request/ChatRequest.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/request/Message.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/request/RequestDto.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/ChatResponse.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/LifeStyleToday.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/MealPatternToday.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/SleepPatternToday.java
  src/main/java/com/kuit/healthmate/chatgpt/service/GptService.java
  src/main/java/com/kuit/healthmate/chatgpt/service/GptServiceImpl.java
  src/main/java/com/kuit/healthmate/chatgpt/util/formatter/LifeStyleTodayFormatter.java
  src/main/java/com/kuit/healthmate/chatgpt/util/formatter/MealPatternTodayFormatter.java
  src/main/java/com/kuit/healthmate/chatgpt/util/formatter/SleepPatternTodayFormatter.java
  src/main/java/com/kuit/healthmate/chatgpt/util/parser/LifeStyleTodayParser.java
  src/main/java/com/kuit/healthmate/chatgpt/util/parser/MealPatternTodayParser.java
  src/main/java/com/kuit/healthmate/chatgpt/util/parser/SleepPatternParser.java
  src/main/java/com/kuit/healthmate/config/ChatGPTConfig.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/LifeStyleDto.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/MealPatternDto.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/PostDiagnosisRequest.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/SleepPatternDto.java
  src/main/java/com/kuit/healthmate/diagnosis/symtom/domain/SymptomInfo.java
  src/main/resources/application.yml
Labels: 기능 추가

#32 [Refactor] : Diagnosis, ,Habit
  src/main/java/com/kuit/healthmate/batch/BatchConfig.java
  src/main/java/com/kuit/healthmate/challenge/common/controller/CommonChallengeController.java
  src/main/java/com/kuit/healthmate/challenge/habit/controller/habitController.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/Habit.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/HabitChecker.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/HabitTime.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/PutCheckHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/SelectedTime.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/request/GetHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/request/PatchEditHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/request/PostCreateHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/request/PutCheckHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/response/GetHabitResponse.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/response/PostCreateHabitResponse.java
  src/main/java/com/kuit/healthmate/challenge/habit/repository/HabitCheckerRepository.java
  src/main/java/com/kuit/healthmate/challenge/habit/repository/HabitRepository.java
  src/main/java/com/kuit/healthmate/challenge/habit/service/HabitService.java
  src/main/java/com/kuit/healthmate/chatgpt/controller/GPTController.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/MealPatternResponse.java
  src/main/java/com/kuit/healthmate/chatgpt/dto/response/SleepPatternResponse.java
  src/main/java/com/kuit/healthmate/config/WebConfig.java
  src/main/java/com/kuit/healthmate/diagnosis/common/controller/DiagnosisController.java
  src/main/java/com/kuit/healthmate/diagnosis/common/service/DiagnosisService.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/DiagnosisResponseDTO.java
  src/main/java/com/kuit/healthmate/diagnosis/dto/PostDiagnosisRequest.java
  src/main/java/com/kuit/healthmate/diagnosis/gpt/domain/GptResult.java
  src/main/java/com/kuit/healthmate/diagnosis/gpt/repository/GptResultRepository.java
  src/main/java/com/kuit/healthmate/diagnosis/life/domain/LifeStyleQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/meal/domain/MealPatternQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/sleep/domain/SleepPatternQuestionnaire.java
  src/main/java/com/kuit/healthmate/diagnosis/symtom/domain/SymptomQuestionnaire.java
  src/main/java/com/kuit/healthmate/global/exception/DiagnosisException.java
  src/main/java/com/kuit/healthmate/global/exception_handler/DiagnosisExceptionHandler.java
  src/main/java/com/kuit/healthmate/global/response/ExceptionResponseStatus.java
  src/main/java/com/kuit/healthmate/user/domain/User.java
Labels: 리팩토링

#37 [Refact] common jwt 처리 및 오류 해결
  .github/workflows/backend-dev-cd.yml
  src/main/java/com/kuit/healthmate/HealthMateApplication.java
  src/main/java/com/kuit/healthmate/batch/BatchScheduler.java
  src/main/java/com/kuit/healthmate/challenge/common/controller/CommonChallengeController.java
  src/main/java/com/kuit/healthmate/global/exception_handler/CommonChallengeExceptionHandler.java
  src/main/java/com/kuit/healthmate/global/response/ExceptionResponseStatus.java
  src/main/resources/application.yml
  src/main/resources/test.sql
Labels: 버그 수정, 리팩토링

#39 [Feat] 코인, 온보딩 정보 [Refactor} GPT 스레드
  src/main/java/com/kuit/healthmate/HealthMateApplication.java
  src/main/java/com/kuit/healthmate/challenge/habit/domain/Habit.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/request/PostCreateHabitRequest.java
  src/main/java/com/kuit/healthmate/challenge/habit/dto/response/PostCreateHabitResponse.java
  src/main/java/com/kuit/healthmate/challenge/habit/service/HabitService.java
  src/main/java/com/kuit/healthmate/chatgpt/controller/GPTController.java
  src/main/java/com/kuit/healthmate/chatgpt/service/GptService.java
  src/main/java/com/kuit/healthmate/chatgpt/service/GptServiceImpl.java
  src/main/java/com/kuit/healthmate/config/AsyncConfig.java
  src/main/java/com/kuit/healthmate/config/WebConfig.java
  src/main/java/com/kuit/healthmate/diagnosis/common/controller/DiagnosisController.java
  src/main/java/com/kuit/healthmate/diagnosis/common/service/DiagnosisService.java
  src/main/java/com/kuit/healthmate/diagnosis/gpt/repository/GptResultRepository.java
  src/main/java/com/kuit/healthmate/user/domain/User.java
  src/main/java/com/kuit/healthmate/user/domain/coin/domain/CoinTransaction.java
  src/main/java/com/kuit/healthmate/user/domain/coin/repository/CoinTransactionRepository.java
  src/main/java/com/kuit/healthmate/user/domain/coin/service/CoinService.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/controller/OnboardingController.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/domain/OnboardingInfo.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/dto/OnboardingRequestDto.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/repository/OnboardingInfoRepository.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/service/OnboardingService.java
Labels: 엔티티, 기능 추가, 리팩토링

#42 [Feat] monitoring(?) 구현
  .github/workflows/backend-dev-cd.yml
  build.gradle
  src/main/resources/application.yml
Labels: 기능 추가, ci/cd

#54 [Refact] checker 문제 해결
  src/main/java/com/kuit/healthmate/challenge/common/service/CommonChallengeServiceImpl.java
  src/main/java/com/kuit/healthmate/challenge/habit/repository/HabitRepository.java
  src/main/java/com/kuit/healthmate/challenge/habit/service/HabitService.java
Labels: 리팩토링

#55 [Feat]supplement edit에서 무엇을 edit하지, 수정 될 영양제의 정보 가져오기, mutiprofile 설정
  build.gradle
  src/main/java/com/kuit/healthmate/challenge/supplement/controller/SupplementController.java
  src/main/java/com/kuit/healthmate/challenge/supplement/domain/SupplementTime.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/CustomTime.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/SupplementEditListResponse.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/SupplementEditResponse.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/SupplementResponse.java
  src/main/java/com/kuit/healthmate/challenge/supplement/service/SupplementService.java
  src/main/resources/application.yml
  src/test/java/com/kuit/healthmate/supplement/SupplementServiceTest.java
Labels: :satellite: 자동 배포

#61 [Refactor] 영양제 수정 화면에 필요한 데이터 형식 수정
  src/main/java/com/kuit/healthmate/challenge/supplement/controller/SupplementController.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/SupplementEditListResponse.java
  src/main/java/com/kuit/healthmate/challenge/supplement/dto/SupplementEditResponse.java
  src/main/java/com/kuit/healthmate/challenge/supplement/repository/SupplementRepository.java
  src/main/java/com/kuit/healthmate/challenge/supplement/service/SupplementService.java
Labels: 리팩토링

#63 [Feat] Docker container 내에서의 모니터링
  infra/docker/crontab
  infra/docker/healthcheck.sh
Labels: 리팩토링

#65 [Feat] 마이페이지에 필요한 정보 보내주기
  src/main/java/com/kuit/healthmate/auth/service/OAuth2UserService.java
  src/main/java/com/kuit/healthmate/challenge/supplement/service/SupplementService.java
  src/main/java/com/kuit/healthmate/user/controller/UserController.java
  src/main/java/com/kuit/healthmate/user/domain/coin/service/CoinService.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/repository/OnboardingInfoRepository.java
  src/main/java/com/kuit/healthmate/user/domain/onboarding/service/OnboardingService.java
  src/main/java/com/kuit/healthmate/user/dto/MyPageResponse.java
  src/main/java/com/kuit/healthmate/user/repository/UserRepository.java
  src/main/java/com/kuit/healthmate/user/service/UserService.java
  src/test/java/com/kuit/healthmate/habit/HabitTest.java
Labels: 기능 추가

#76 [Refact] supplement 조회 로직 변경
  .github/workflows/backend-dev-cd.yml
  src/main/java/com/kuit/healthmate/challenge/common/service/CommonChallengeServiceImpl.java
Labels: 리팩토링
